version: "3"

services:
  grafana:
    image: grafana/grafana-oss
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000 
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password

volumes:
  grafana_data: