version: "3"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    restart: always
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3
    restart: always
    ports:
      - 9093:9093
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://172.17.0.1:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 5s
      timeout: 5s
      retries: 10

  kowl:
    image: quay.io/cloudhut/kowl:v1.1.0
    restart: on-failure
    volumes:
      - ./configs/kowl.yml:/etc/kowl/config.yml:ro
    ports:
      - 8080:8080
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yml
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  zookeeper_data:
  kafka_data: